INSERT INTO achievement (title, description, rarity, points, created_at, updated_at)
VALUES
    ('PEEPERS', 'Get 100 subscribers', 3, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EVIL COMMENTATOR', 'Leave 100 comments', 2, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BLOGGER', 'Get 1000 subscribers', 1, 1000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('OPINION LEADER', 'Publish 1000 posts', 3, 1000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RECURSION RECURSION', 'Get 30 achievements', 4, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BUSINESSMAN', 'Create 5 projects', 3, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('I LOVE EVERYONE', 'Leave 1000 likes under posts', 1, 1000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
